### ISSUE TITLE
Environment variables not being passed to PHP-FPM

### ISSUE THREAD

**Issue by Inumedia** [tiredofit/docker-nginx-php-fpm#1]
When running scripts inside of this container it doesn't seem to pass any of the environment variables to the actual PHP scripts

**Comment by tiredofit** [comment]
You would need to alter your php-fpm.conf file to accept environment variables. In these images I have limited it, but it is an easy fix. I believe it should be at the bottom of the file to make your modifications. Personally I find it more a risk to have my environment variables exposed to the PHP engine due to the nature of some of the contents, but you are welcome to modify and make it work as you would like!

**Comment by Inumedia** [comment]
👌

**Comment by spumer** [comment]
@tiredofit 
Can you just ADD env variable to enable this feauture?

This prevent googling and manual fixing for people who whants pass env variables.

As i know S6 allow clear env and docker did it by himself. Are you shure `clear_env` in PHP is actual for Docker?
